version: "2"
services:
  nginx:
    build: nginx
    ports:
      - "8000:80"
    links:
      - web:web
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
