version: "2"
services:
  nginx:
    image: nreoch9/adentify-mern-nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes_from:
      - web
    links:
      - web:web
  web:
    image: nreoch9/adentify-mern:latest
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - /usr/src/app/dist
    environment:
      NODE_ENV: production
