export const FETCH_AD_RESPONSES = "FETCH_AD_RESPONSES";
export const RESET_AD_RESPONSES = "RESET_AD_RESPONSES";
export const SAVE_AD_REQUESTS = "SAVE_AD_REQUESTS";
export const SAVE_SUBMITTED_REQUESTS = "SAVE_SUBMITTED_REQUESTS";
export const RESET_SAVED_RESPONSES = "RESET_SAVED_RESPONSES";
export const UPDATE_SAVED_RESPONSES = "UPDATE_SAVED_RESPONSES";
